C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask_sqlalchemy\__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2021-02-20 09:15:24,117] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Umberto\Desktop\flaskProject22\blog\main\views.py", line 7, in index
    return render_template('main/index.html')
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: main/index.html
127.0.0.1 - - [20/Feb/2021 09:15:24] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\app.py", line 1879, in handle_exception
    server_error = handler(server_error)
  File "C:\Users\Umberto\Desktop\flaskProject22\blog\main\errors.py", line 14, in internal_server_error
    return render_template('main/error.html', error_code=500, error_msg="Errore interno al server!"), 500
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\Umberto\PycharmProjects\flaskProject22\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: main/error.html